language: node_js
node_js:
- stable
sudo: false
before_install:
- yarn global add bumpr@^2.7.2
install:
- yarn install
before_script:
- bumpr check
script:
- yarn test
- bumpr bump
after_success:
- bumpr publish
